#!/usr/bin/env bash
# rbops/gen-prompts.sh — materialise phases/<id>/PROMPT.md from rbops/phases.json.
#
# The manifest is the single source of truth. PROMPT.md files are GENERATED and
# committed so a phase is human-readable in the tree, but they are never
# hand-edited: edit phases.json and re-run this.
#
#   ./rbops/gen-prompts.sh          regenerate all
#   ./rbops/gen-prompts.sh --check  fail if any PROMPT.md differs from the manifest
#
# Two implementation rules learned the hard way:
#
#  1. Every heredoc carrying literal markdown backticks MUST be quoted
#     (<<'EOF'). An unquoted heredoc performs command substitution on
#     backticks, so a template containing `cargo test` would try to EXECUTE
#     cargo test on the machine running the generator.
#
#  2. `jq | while read` pipelines get `tr -d '\r'`. A Windows jq.exe under
#     WSL emits CRLF, which yields a phase id of "phase-001\r" and silently
#     creates a directory with a carriage return in its name. Worse, a
#     *nested* jq.exe slurps the outer pipe and kills the loop after one
#     iteration. Honour $JQ so a native Linux jq can be substituted when
#     testing outside CI.
set -uo pipefail

PHASES="${RBOPS_PHASES:-rbops/phases.json}"
JQ="${JQ:-jq}"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

command -v "$JQ" >/dev/null 2>&1 || { echo "jq is required (set JQ=/path/to/jq)" >&2; exit 2; }
[ -f "$PHASES" ] || { echo "no manifest at $PHASES" >&2; exit 2; }
"$JQ" -e '.phases | type == "array"' "$PHASES" >/dev/null || { echo "manifest invalid" >&2; exit 2; }

# --------------------------------------------------------------- render phase
# render <phase-json-string> <output-path>
# Renders a complete PROMPT.md from one phase object into $2.
render() {
  local p="$1" out="$2"
  local id title sev risk goal finding deps tmo accepts edge_rows

  id="$(printf '%s' "$p"      | "$JQ" -r '.id')"
  title="$(printf '%s' "$p"   | "$JQ" -r '.title')"
  sev="$(printf '%s' "$p"     | "$JQ" -r '.severity')"
  risk="$(printf '%s' "$p"    | "$JQ" -r '.risk')"
  goal="$(printf '%s' "$p"    | "$JQ" -r '.goal')"
  finding="$(printf '%s' "$p" | "$JQ" -r '.finding')"
  deps="$(printf '%s' "$p"    | "$JQ" -r 'if (.depends_on|length)==0 then "_none_" else (.depends_on|join(", ")) end')"
  tmo="$(printf '%s' "$p"     | "$JQ" -r '.timeout_min // 120')"
  accepts="$(printf '%s' "$p" | "$JQ" -r '.accept[] | "- [ ] \(.)"')"
  # must_touch and failure_assert are gate rules the agent can fail on. The
  # manifest carried them but the prompt did not, so an agent reading only its
  # brief could not know it had to change src/ at all - the one requirement that
  # stops a phase being "tests plus prose".
  must="$(printf '%s' "$p"    | "$JQ" -r 'if (.must_touch // []) | length > 0 then (.must_touch | join(" or ")) else "" end')"
  failmode="$(printf '%s' "$p" | "$JQ" -r '.failure_assert // "required"')"
  edge_rows="$("$JQ" -r '.test_policy.edge_matrix[] | "- [ ] \(.) — covered / N/A + why"' "$PHASES")"

  [ -n "$id" ] || return 1

  {
    printf '# %s — %s\n\n' "$id" "$title"
    printf '<!-- GENERATED by rbops/gen-prompts.sh from rbops/phases.json. DO NOT EDIT. -->\n\n'
    printf '| | |\n|---|---|\n'
    printf '| Severity | `%s` |\n' "$sev"
    printf '| Risk | `%s` |\n' "$risk"
    printf '| Depends on | %s |\n' "$deps"
    printf '| Timeout | %s min |\n' "$tmo"
    if [ -n "$must" ]; then
      printf '| Must change | `%s` |\n' "$must"
    fi
  } > "$out"

  if [ -n "$must" ]; then
    cat >> "$out" <<EOF

## You must change \`$must\`

This phase declares \`must_touch: [$must]\`. The gate fails the phase unless at
least one changed file falls under it. Writing tests, documentation or a report
is not enough — if you finish without touching that area, the phase fails on
exactly that check.

EOF
  fi

  if [ "$failmode" = "not_applicable" ]; then
    cat >> "$out" <<'EOF'
## The failure-assertion rule does not apply here

This phase declares `failure_assert: not_applicable`, so the gate does NOT
require a test asserting that a failure is produced. Your subsystem reports
problems as diagnostics or emits documents, so there is no `Result::Err` to
assert on. Every other test rule still applies in full.

EOF
  fi

  cat >> "$out" <<'EOF'

## Evidence — verified finding

```
__FINDING__
```

**Re-verify this before you change anything.** If the finding no longer
reproduces on `main`, stop and write that to `FINDINGS.md` — a stale phase must
never be "fixed" by inventing a change.

## Goal

__GOAL__

## Method

1. Read `AGENTS.md` in full. Obey every hard rule; they are not negotiable.
2. Reproduce the finding. Record the exact command and the exact wrong output.
3. Write the failing test FIRST. Watch it fail. Do not touch production code
   until you have a red test that fails for the right reason.
4. Make the smallest change that turns it green.
5. Run the four gates yourself before claiming anything:

   ```bash
   cargo fmt --all -- --check
   cargo clippy --all-targets -- -D warnings
   cargo test --all-targets
   ./rbops/verify.sh __ID__
   ```

6. Write `REPORT.md` in the exact shape required by `AGENTS.md` section 4.

## Definition of done

__ACCEPTS__

## Test requirements — non-negotiable

From `AGENTS.md` section 3. Tick each row that applies to this change. For
every row you do NOT cover, write one line in `REPORT.md` saying why.

__EDGE_ROWS__

You must also:

- at least 3 new `#[test]` functions (or at least 2 new Redblue `test` blocks).
  This is a floor, not a target: it catches "no verification at all". Whether
  your tests COVER the change is judged by the reviewer, and an untested branch
  is a MAJOR finding that sends the phase back.
- at least 1 test named `edge_*`
- at least 1 test that asserts a **failure** is produced, not just a success
- zero new `#[ignore]`, `// skip`, or `allow(clippy::` suppressions
- zero newly-failing pre-existing tests

## Constraints

- Do not touch `.github/workflows/`, `rbops/`, `.opencode/agent/`, or
  `rbops/phases.json`. The gate rejects these paths, and the bot token has no
  `workflows` scope so a push touching `.github/` is refused by GitHub.
- Do not weaken, delete or re-scope any existing test.
- Do not change the language surface listed in `phases/INVARIANTS.md`.
- Keep the diff on-topic. A refactor smuggled into a bug-fix phase is a
  review BLOCKER.
- Do not update README or ROADMAP to claim this works. Update them only when
  the gate is green and you have run the examples yourself.

## If you are blocked

Do not fake progress. Write what you tried, the exact error, and what you
believe is required into `FINDINGS.md`, then stop.

A blocked phase with an honest report is worth more than a green phase with a
lie in it. `verify.sh` will reject the phase anyway; a fabrication only adds a
blocking review finding on top.
EOF

  # Substitute placeholders. awk's gsub() cannot carry a multi-line replacement
  # through -v safely, so the dynamic blocks are staged in temp files and read
  # via ENVIRON.
  local d1 d2 d3 d4 tmp
  d1="$(mktemp)"; d2="$(mktemp)"; d3="$(mktemp)"; d4="$(mktemp)"
  tmp="$(mktemp)"
  printf '%s' "$finding"   > "$d1"
  printf '%s' "$goal"      > "$d2"
  printf '%s' "$accepts"   > "$d3"
  printf '%s' "$edge_rows" > "$d4"

  RB_ID="$id" RB_F1="$d1" RB_G="$d2" RB_A="$d3" RB_E="$d4" \
  awk '
    function slurp(f) { s = ""; while ((getline l < f) > 0) s = s l "\n"; close(f); sub(/\n$/, "", s); return s }
    BEGIN {
      finding = slurp(ENVIRON["RB_F1"]); goal = slurp(ENVIRON["RB_G"])
      acc     = slurp(ENVIRON["RB_A"]); edge   = slurp(ENVIRON["RB_E"])
      id      = ENVIRON["RB_ID"]
    }
    {
      line = $0
      gsub(/__FINDING__/,   finding, line)
      gsub(/__GOAL__/,      goal,    line)
      gsub(/__ACCEPTS__/,   acc,     line)
      gsub(/__EDGE_ROWS__/, edge,    line)
      gsub(/__ID__/,        id,      line)
      print line
    }
  ' "$out" > "$tmp" && mv "$tmp" "$out"

  rm -f "$d1" "$d2" "$d3" "$d4" "$tmp"
}

# ------------------------------------------------------------------- main loop
RC=0
"$JQ" -c '.phases[]' "$PHASES" | tr -d '\r' | while read -r p; do
  p="${p%$'\r'}"
  id="$(printf '%s' "$p" | "$JQ" -r '.id' | tr -d '\r')"
  [ -n "$id" ] || continue
  target="phases/$id/PROMPT.md"

  if [ "$CHECK" = "1" ]; then
    tmp="$(mktemp)"
    render "$p" "$tmp" || { echo "ERR: render failed for $id"; rm -f "$tmp"; exit 1; }
    if [ ! -f "$target" ]; then
      echo "MISSING: $target"
      rm -f "$tmp"; exit 1
    fi
    if ! diff -u "$target" "$tmp" > /dev/null; then
      echo "STALE:   $target"
      diff -u "$target" "$tmp" | head -20
      rm -f "$tmp"; exit 1
    fi
    rm -f "$tmp"
    printf 'current: %s\n' "$target"
  else
    mkdir -p "phases/$id"
    render "$p" "$target" || { echo "ERR: render failed for $id"; exit 1; }
    printf 'generated %s\n' "$target"
  fi
done || RC=$?

exit "$RC"